-- Durable per-user API rate limiting for expensive content generation requests.
create table if not exists public.api_rate_limit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete cascade,
  bucket text not null,
  created_at timestamptz not null default now()
);

create index if not exists api_rate_limit_events_lookup_idx
  on public.api_rate_limit_events (actor_id, bucket, created_at desc);

alter table public.api_rate_limit_events enable row level security;
revoke all on table public.api_rate_limit_events from anon, authenticated;

create or replace function public.check_and_record_rate_limit(
  bucket_name text,
  request_limit integer default 10,
  window_seconds integer default 60
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_actor uuid := (select auth.uid());
  recent_count integer;
begin
  if current_actor is null then raise exception 'Authentication required'; end if;
  if bucket_name is null or char_length(trim(bucket_name)) < 1 or char_length(bucket_name) > 100 then raise exception 'Invalid rate-limit bucket'; end if;
  if request_limit < 1 or request_limit > 1000 then raise exception 'Invalid request limit'; end if;
  if window_seconds < 1 or window_seconds > 86400 then raise exception 'Invalid rate-limit window'; end if;

  perform pg_advisory_xact_lock(hashtextextended(current_actor::text || ':' || trim(bucket_name), 0));

  select count(*) into recent_count
  from public.api_rate_limit_events
  where actor_id = current_actor
    and bucket = trim(bucket_name)
    and created_at >= now() - make_interval(secs => window_seconds);

  if recent_count >= request_limit then return false; end if;

  insert into public.api_rate_limit_events (actor_id, bucket)
  values (current_actor, trim(bucket_name));

  delete from public.api_rate_limit_events
  where created_at < now() - interval '24 hours';

  return true;
end;
$$;

revoke all on function public.check_and_record_rate_limit(text, integer, integer) from public;
grant execute on function public.check_and_record_rate_limit(text, integer, integer) to authenticated;
